In [90]:
import numpy as np
from typing import Union
import random

## Task 1

In [156]:
class HammingCode:
      '''
      
      Input a 4-bit binary value input to see Hamming's Code in action. 
      List or a one long int is accepted as input, as long as it only includes 4-bits.
      
      '''
      
      def __init__(self, bit_input: Union[int, list]):
            # if/else to accept two types of inputs. 
            if type(bit_input) == list:
                  self.bit_input = np.array(bit_input)
            else:
                  self.bit_input = np.array([int(x) for x in (str(bit_input))])
            
            # Error handling: If max bit > 1 or length bigger or smaller than 4, raise error
            if max(self.bit_input) > 1:
                  raise ValueError(f"Only takes binary values (1's or 0's). Your input included {max(self.bit_input)}")
            elif len(self.bit_input) != 4:
                  raise SyntaxError(f"Input can be no more or less than 4-bits. You inputted {len(self.bit_input)} bits")
            
            # Calling code_word method when object is initialized
            self.code_word_generator() 
            
      
      def code_word_generator(self):
            """
            Transforms the 4-bit input value to a 7-bit binary vector codeword.
            """
            self.code_word = self.bit_input
            
            self.parity_bits = {
                  #key = bit position (not at index 0), 
                  #value = encoded parity bit (placeholder).
                  1: [0 if (self.code_word[0] + self.code_word[1] + self.code_word[3])%2 == 0 else 1][0], #Using sum, to transform 
                  2: [0 if (self.code_word[0] + self.code_word[2] + self.code_word[3])%2 == 0 else 1][0],
                  4: [0 if (self.code_word[1] + self.code_word[2] + self.code_word[3])%2 == 0 else 1][0],
            }
            
            # Add parity values add the right index to form 7-bit vector code word
            for key in self.parity_bits:
                  self.code_word = np.insert(self.code_word, key-1, self.parity_bits[key])
      
      # Adding represent method for nicer output of codeword
      def __repr__(self):
            return f"7-bit codeword of input {str(self.bit_input)}: \n{str(self.code_word):-^34s}"
      
      
      def parity_check(self, test=False):
            ''' 
            Check if 4-bit input have been corrupted.
            
            test variable allows to deliberately corrupt a input, to see parity check on a corrupted input
            '''
            parity_check_matrix = np.array([[1,0,1,0,1,0,1],
                                            [0,1,1,0,0,1,1],
                                            [0,0,0,1,1,1,1]])
            
            if test == True:
                  disrupted_codeword = self.code_word.copy()
                  variable_to_disrupt = random.choice([2,4,5,6])
                  if disrupted_codeword[variable_to_disrupt] == 0:
                        disrupted_codeword[variable_to_disrupt] = 1
                  else:
                        disrupted_codeword[variable_to_disrupt] = 0
                  
                  parity_check_dot_product = parity_check_matrix.dot(disrupted_codeword)


                  parity_check = np.mod(parity_check_dot_product, 2)
                  parity_errors = list(np.where(parity_check==1)[0])

                  if parity_errors == [0,1]:
                        bit_error = 'D1'
                  elif parity_errors == [0,2]:
                        bit_error = 'D2'      
                  elif parity_errors == [1,2]:
                        bit_error = 'D3'      
                  else:
                        bit_error = 'D4'
                        
                  return f'Test corruption (at bit position {variable_to_disrupt+1})... Parity check and modulo 2 operation, returns: {parity_check}\nData bit corruption have occured at {bit_error}\n' 
            else:
                  parity_check_dot_product = parity_check_matrix.dot(self.code_word)
                  
                  parity_check = np.mod(parity_check_dot_product, 2)
                  
                  return f'The data have not been corrupted, as the parity check and modulo 2 oepration returns: {parity_check}'
                  
            

# Task 2

In [157]:
class Decoder:
      def __init__(self, code_word: Union[int, list]):
            # if/else to accept two types of inputs. 
            if type(code_word) == list:
                  self.code_word = np.array(code_word)
            elif type(code_word) == np.ndarray:
                  self.code_word = code_word
            else:
                  self.code_word = np.array([int(x) for x in (str(code_word))])
            
            # Error handling: If max bit > 1 or length bigger or smaller than 4, raise error
            if max(self.code_word) > 1:
                  raise ValueError(f"Only takes binary values (1's or 0's). Your input included {max(self.bit_input)}")
            elif len(self.code_word) != 7:
                  raise SyntaxError(f"Input can be no more, or less, than 7-bits. You inputted {len(self.bit_input)} bits")
            
            # Calling code_word method when object is initialized
            self.decode()
      
      
      
      def decode(self):
            decoder_matrix = np.array([[0,0,1,0,0,0,0],
                                       [0,0,0,0,1,0,0],
                                       [0,0,0,0,0,1,0],
                                       [0,0,0,0,0,0,1]])
            
            self.original_word = decoder_matrix.dot(self.code_word)
            #3return decoder_matrix.dot(self.code_word)
            

# Task 3

In [158]:
b1 = HammingCode(1011)
b2 = HammingCode(1111)
b3 = HammingCode(1000)
b4 = HammingCode(1010)

In [159]:
print(b1.bit_input, ' encoded, becomes: ', b1.code_word)
print(b2.bit_input, ' encoded, becomes: ', b2.code_word)
print(b3.bit_input, ' encoded, becomes: ', b3.code_word)
print(b4.bit_input, ' encoded, becomes: ', b4.code_word)

[1 0 1 1]  encoded, becomes:  [0 1 1 0 0 1 1]
[1 1 1 1]  encoded, becomes:  [1 1 1 1 1 1 1]
[1 0 0 0]  encoded, becomes:  [1 1 1 0 0 0 0]
[1 0 1 0]  encoded, becomes:  [1 0 1 1 0 1 0]


In [160]:
print(b1.parity_check())
print(b2.parity_check())
print(b3.parity_check())
print(b4.parity_check())

The data have not been corrupted, as the parity check and modulo 2 oepration returns: [0 0 0]
The data have not been corrupted, as the parity check and modulo 2 oepration returns: [0 0 0]
The data have not been corrupted, as the parity check and modulo 2 oepration returns: [0 0 0]
The data have not been corrupted, as the parity check and modulo 2 oepration returns: [0 0 0]


In [162]:
print('Test corruption of codeword at random data bit positions')
print(b1.parity_check(True))
print(b2.parity_check(True))
print(b3.parity_check(True))
print(b4.parity_check(True))

Test corruption of codeword at random data bit positions
Test corruption (at bit position 6)... Parity check and modulo 2 operation, returns: [0 1 1]
Data bit corruption have occured at D3

Test corruption (at bit position 3)... Parity check and modulo 2 operation, returns: [1 1 0]
Data bit corruption have occured at D1

Test corruption (at bit position 6)... Parity check and modulo 2 operation, returns: [0 1 1]
Data bit corruption have occured at D3

Test corruption (at bit position 5)... Parity check and modulo 2 operation, returns: [1 0 1]
Data bit corruption have occured at D2



In [163]:
codeword_1 = Decoder(b1.code_word)
codeword_2 = Decoder(b2.code_word)
codeword_3 = Decoder(b3.code_word)
codeword_4 = Decoder(b4.code_word)

In [164]:
print(codeword_1.code_word, ' decoded, becomes: ', codeword_1.original_word)
print(codeword_2.code_word, ' decoded, becomes: ', codeword_2.original_word)
print(codeword_3.code_word, ' decoded, becomes: ', codeword_3.original_word)
print(codeword_4.code_word, ' decoded, becomes: ', codeword_4.original_word)

[0 1 1 0 0 1 1]  decoded, becomes:  [1 0 1 1]
[1 1 1 1 1 1 1]  decoded, becomes:  [1 1 1 1]
[1 1 1 0 0 0 0]  decoded, becomes:  [1 0 0 0]
[1 0 1 1 0 1 0]  decoded, becomes:  [1 0 1 0]


In [98]:
test = np.array([1,0,1,0])

In [118]:
test_list = list(np.where(test==1)[0])

In [119]:
if test_list == [0,2]:
    print(True)

True
